apiVersion: apps/v1
kind: Deployment
metadata:
  name: mail-lab-back-deployment
  namespace: default
  labels:
    app: mail-lab
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mail-lab
      type: backend
  template:
    metadata:
      labels:
        app: mail-lab
        type: backend
    spec:
      containers:
      - name: mail-lab
        image: fleynaro/web-mail-lab:backend-v1.0
        imagePullPolicy: IfNotPresent
        env:
        - name: URL_PREFIX
          value: "/labs/mail"
        ports:
          - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: mail-lab-back-service
  namespace: default
spec:
  selector:
    app: mail-lab
    type: backend
  ports:
    - port: 8080
      targetPort: 80